# Generated by Django 5.1.4 on 2025-05-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_job_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xét duyệt'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối'), ('hired', 'Đã tuyển')], default='pending', max_length=20),
        ),
    ]
